### ISSUE TITLE
Getting the error "Body is too long" while trying to create a PR comment

### ISSUE THREAD

**Issue by roerohan** [davelosert/vitest-coverage-report-action#214]
When the action tries to create a PR comment, I'm getting an error:

![image](https://github.com/davelosert/vitest-coverage-report-action/assets/42958812/5d41377f-8803-427f-bf6f-7353fc775db7)

Is there any way to divide the coverage report into multiple comments?

**Comment by davelosert** [comment]
Hey @roerohan , thank you for opening the issue. This was already reported in #190 and is due to the file-coverage-report being too large to post to an Issue.

There is already some work being done in #192 allow to only showcase the changed files in a PR to mitigate this, but it's been inactive for a while. Will try to finish it up myself.

I am also planning to add an option (#191) to disable having the file reporting altogether.

I will close this issue as duplicate, but I am happy to answer any upcoming questions or have discussons in #190 🙂

**Comment by davelosert** [comment]
@roerohan : This should be fixed now (at least for most PRs) by only showcasing the changed files in the file-coverage on default.

Let me know if it fixed it for you.
